//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListaEstudiante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListaEstudianteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int IngresarEstudiante(string ci, string nombre, string fechaNa, string telefono, string depto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresarEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IngresarEstudianteAsync(string ci, string nombre, string fechaNa, string telefono, string depto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizarEstudiante(string ci, string nombre, string fechaNa, string telefono, string depto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ActualizarEstudianteAsync(string ci, string nombre, string fechaNa, string telefono, string depto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarEstudiante(string ci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EliminarEstudianteAsync(string ci);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp3.ServiceReference1.WebService1Soap>, WindowsFormsApp3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet ListaEstudiante() {
            return base.Channel.ListaEstudiante();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListaEstudianteAsync() {
            return base.Channel.ListaEstudianteAsync();
        }
        
        public int IngresarEstudiante(string ci, string nombre, string fechaNa, string telefono, string depto) {
            return base.Channel.IngresarEstudiante(ci, nombre, fechaNa, telefono, depto);
        }
        
        public System.Threading.Tasks.Task<int> IngresarEstudianteAsync(string ci, string nombre, string fechaNa, string telefono, string depto) {
            return base.Channel.IngresarEstudianteAsync(ci, nombre, fechaNa, telefono, depto);
        }
        
        public string ActualizarEstudiante(string ci, string nombre, string fechaNa, string telefono, string depto) {
            return base.Channel.ActualizarEstudiante(ci, nombre, fechaNa, telefono, depto);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarEstudianteAsync(string ci, string nombre, string fechaNa, string telefono, string depto) {
            return base.Channel.ActualizarEstudianteAsync(ci, nombre, fechaNa, telefono, depto);
        }
        
        public string EliminarEstudiante(string ci) {
            return base.Channel.EliminarEstudiante(ci);
        }
        
        public System.Threading.Tasks.Task<string> EliminarEstudianteAsync(string ci) {
            return base.Channel.EliminarEstudianteAsync(ci);
        }
    }
}
